# Generated by Django 3.1.12 on 2023-04-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=250)),
                ('modelResult', models.CharField(max_length=50)),
                ('resumeData', models.CharField(max_length=2000)),
            ],
        ),
    ]
