# Generated by Django 3.1.12 on 2023-04-19 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeClassifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hiredCanditate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=255)),
                ('commission', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('agency', models.CharField(max_length=255)),
                ('agency_contact', models.CharField(max_length=75)),
            ],
        ),
    ]
