# Generated by Django 3.1.12 on 2023-04-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeClassifier', '0002_hiredcanditate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiredcanditate',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
