# Generated by Django 3.1.12 on 2023-04-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeClassifier', '0003_hiredcanditate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('company', models.CharField(max_length=255)),
                ('hiredNumber', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
